# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- Gemfile
- Gemfile.lock
- garth-jekyll-theme.gemspec

# 2. Installed Gems
plugins:
- jekyll-paginate
- jekyll-paginate-multiple

# 3. Gem settings
paginate_multiple:
  - paginate: 3
    paginate_path: '/blog/page:num'
    sub_dir: '/blogs'
  - paginate: 5
    paginate_path: '/poem/page:num'
    sub_dir: '/poems'

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/London # Timezone for blog posts and alike

# 5. Collections
collections:
  blogs:
    title: Blog # Needed for Siteleaf
    output: true
    description: "Some random thoughts and daydreams :)" # The post list page content
  poems:
    title: Poem # Needed for Siteleaf
    output: true
    description: 
      "A collection of Chinese poem translations, 
      with [Kevin Zhou](https://knzhou.github.io/) :)" # The post list page content

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page # Default layout
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post # Default layout
  -
    scope:
      path: ""
      type: poems
    values:
      layout: poem # Default layout

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
title: "Yiwen Song" # Site name or title
logo: "/assets/logo.svg" # Site logo
# favicon: "/favicon.ico" # Uncomment to add custom favicon, or leave as is to use site logo
description: "A really basic theme for Jekyll, using the official Jekyll theme implementation" # Site description and default description
baseurl: ""
lang: en-GB
destination: docs/
